on: push
name: ðŸš€ Deploy website on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Change Gradle Command Permission
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew bootWar
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: cicdsample
        path: build/libs/ROOT.war

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: cicdsample
    
      - name: Upload war File
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir : ~/tomcat/webapps/
  
  Restart-Server:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Shutdown Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: ~/tomcat/bin/shutdown.sh

      - name: Start Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: ~/tomcat/bin/startup.sh
    
