on: push
name: ðŸš€ Deploy Website on Push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Change Gradle Command Permission
      run: chmod +x ./gradlew
      
    - name: Build war with Gradle
      run: ./gradlew bootWar
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: cicdsample
        path: build/libs/ROOT.war

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: cicdsample
    
      - name: Upload war File
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir : ./tomcat/webapps/
  
  Restart-Server:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Restart Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          JAVA_HOME: "/usr/local/jdk17"
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script_stop: true
          envs: JAVA_HOME
          script: |
            ~/tomcat/bin/shutdown.sh
            ~/tomcat/bin/startup.sh
    
